# Data Cleaning

In [79]:
import pandas as pd

In [80]:
housing_assistance = pd.read_csv('materials/housing_assistance.csv')

In [81]:
housing_assistance.shape

(26844, 23)

In [82]:
housing_assistance.head()

,Disaster,State,County,City,Zip Code,Valid Registrations,Average FEMA Inspected Damage,Total Inspected,Total Damage,No FEMA Inspected Damage,...,"FEMA Inspected Damage > $30,000",Approved for FEMA Assistance,Total Approved IHP Amount,Repair/Replace Amount,Rental Amount,Other Needs Amount,"Approved between $1 and $10,000","Approved between $10,001 and $25,000","Approved between $25,001 and Max",Total Max Grants
0,4344,CA,Butte (County),BANGOR,95914,54,"$48,015",27,"$1,296,415",7,...,12,19,"$407,336","$344,897","$29,154","$33,285",6,2,11,8
1,4344,CA,Butte (County),BERRY CREEK,95916,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
2,4344,CA,Butte (County),BIGGS,95917,10,$0,5,$0,5,...,0,1,$500,$0,$0,$500,1,0,0,0
3,4344,CA,Butte (County),CHICO,95926,66,$0,21,$0,21,...,0,3,"$1,500",$0,$0,"$1,500",3,0,0,0
4,4344,CA,Butte (County),CHICO,95927,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0

In [83]:
housing_assistance.columns = ['disaster', 'state', 'county', 'city', 'zip', 'valid_registrations', 'avg_inspected_damage',
                             'total_inspected', 'total_damage', 'no_inspected_damage', 'damage_1_10000', 'damage_10000_20000',
                             'damage_20000_30000', 'damage_30000_max', 'approved_for_assistance', 'total_approved_amt',
                             'repair_replace_amt', 'rental_amt', 'other_needs_amt', 'approved_1_10000', 'approved_10001_25000',
                             'approved_25001_max', 'total_max_grants']

In [84]:
for col in housing_assistance.columns:
    housing_assistance[col] = housing_assistance[col].apply(lambda x: str(x).strip('$'))
    housing_assistance[col] = housing_assistance[col].apply(lambda x: str(x).replace(',', ''))
    housing_assistance[col] = housing_assistance[col].apply(lambda x: int(x) if x.isdigit() else x)

In [85]:
housing_assistance.dtypes.value_counts()

int64     19
object     4
dtype: int64

In [86]:
housing_assistance.head()

,disaster,state,county,city,zip,valid_registrations,avg_inspected_damage,total_inspected,total_damage,no_inspected_damage,...,damage_30000_max,approved_for_assistance,total_approved_amt,repair_replace_amt,rental_amt,other_needs_amt,approved_1_10000,approved_10001_25000,approved_25001_max,total_max_grants
0,4344,CA,Butte (County),BANGOR,95914,54,48015,27,1296415,7,...,12,19,407336,344897,29154,33285,6,2,11,8
1,4344,CA,Butte (County),BERRY CREEK,95916,2,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,4344,CA,Butte (County),BIGGS,95917,10,0,5,0,5,...,0,1,500,0,0,500,1,0,0,0
3,4344,CA,Butte (County),CHICO,95926,66,0,21,0,21,...,0,3,1500,0,0,1500,3,0,0,0
4,4344,CA,Butte (County),CHICO,95927,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [87]:
disasters = pd.read_csv('materials/filtered_incident_type.csv')

disasters = disasters[['Disaster Number', 'Incident Type']]
disasters.head()

   Disaster Number Incident Type
0             4416         Flood
1             4416         Flood
2             4416         Flood
3             4416         Flood
4             4416         Flood

In [88]:
disaster_codes = (set(zip(disasters['Disaster Number'].values, disasters['Incident Type'].values)))

In [89]:
codes_dict = {num: dis for num, dis in disaster_codes}

In [90]:
housing_assistance['disaster_type'] = housing_assistance['disaster'].map(codes_dict)

In [ ]:
housing_assistance.dropna(inplace=)

In [91]:
housing_assistance.to_csv('materials/housing_cleaned.csv', index=False)