# Data Cleaning

In [27]:
import pandas as pd

In [43]:
katrina_fema = pd.read_csv('materials/Katrinaplus.csv').drop(0, axis=0)

In [44]:
housing_assistance = pd.read_csv('materials/housing_assistance.csv')

In [30]:
housing_assistance.shape

(26844, 23)

In [31]:
housing_assistance.head()

,Disaster,State,County,City,Zip Code,Valid Registrations,Average FEMA Inspected Damage,Total Inspected,Total Damage,No FEMA Inspected Damage,...,"FEMA Inspected Damage > $30,000",Approved for FEMA Assistance,Total Approved IHP Amount,Repair/Replace Amount,Rental Amount,Other Needs Amount,"Approved between $1 and $10,000","Approved between $10,001 and $25,000","Approved between $25,001 and Max",Total Max Grants
0,4344,CA,Butte (County),BANGOR,95914,54,"$48,015",27,"$1,296,415",7,...,12,19,"$407,336","$344,897","$29,154","$33,285",6,2,11,8
1,4344,CA,Butte (County),BERRY CREEK,95916,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
2,4344,CA,Butte (County),BIGGS,95917,10,$0,5,$0,5,...,0,1,$500,$0,$0,$500,1,0,0,0
3,4344,CA,Butte (County),CHICO,95926,66,$0,21,$0,21,...,0,3,"$1,500",$0,$0,"$1,500",3,0,0,0
4,4344,CA,Butte (County),CHICO,95927,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0

In [47]:
housing_assistance.columns = ['disaster', 'state', 'county', 'city', 'zip', 'valid_registrations', 'avg_inspected_damage',
                             'total_inspected', 'total_damage', 'no_inspected_damage', 'damage_1_10000', 'damage_10000_20000',
                             'damage_20000_30000', 'damage_30000_max', 'approved_for_assistance', 'total_approved_amt',
                             'repair_replace_amt', 'rental_amt', 'other_needs_amt', 'approved_1_10000', 'approved_10001_25000',
                             'approved_25001_max', 'total_max_grants']

katrina_fema.columns = ['disaster', 'state', 'county', 'city', 'zip', 'valid_registrations', 'avg_inspected_damage',
                             'total_inspected', 'total_damage', 'no_inspected_damage', 'damage_1_10000', 'damage_10000_20000',
                             'damage_20000_30000', 'damage_30000_max', 'approved_for_assistance', 'total_approved_amt',
                             'repair_replace_amt', 'rental_amt', 'other_needs_amt', 'approved_1_10000', 'approved_10001_25000',
                             'approved_25001_max', 'total_max_grants']

In [48]:
def cleaning(df):
    for col in df.columns:
        df[col] = df[col].apply(lambda x: str(x).strip('$'))
        df[col] = df[col].apply(lambda x: str(x).replace(',', ''))
        df[col] = df[col].apply(lambda x: int(x) if x.isdigit() else x)
        df['county'] = df['county'].apply(lambda x: x.replace('(County)', ''))
        df['county'] = df['county'].apply(lambda x: x.replace('(Parish)', ''))

In [49]:
housing_assistance

,disaster,state,county,city,zip,valid_registrations,avg_inspected_damage,total_inspected,total_damage,no_inspected_damage,...,damage_30000_max,approved_for_assistance,total_approved_amt,repair_replace_amt,rental_amt,other_needs_amt,approved_1_10000,approved_10001_25000,approved_25001_max,total_max_grants
0,4344,CA,Butte (County),BANGOR,95914,54,"$48,015",27,"$1,296,415",7,...,12,19,"$407,336","$344,897","$29,154","$33,285",6,2,11,8
1,4344,CA,Butte (County),BERRY CREEK,95916,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
2,4344,CA,Butte (County),BIGGS,95917,10,$0,5,$0,5,...,0,1,$500,$0,$0,$500,1,0,0,0
3,4344,CA,Butte (County),CHICO,95926,66,$0,21,$0,21,...,0,3,"$1,500",$0,$0,"$1,500",3,0,0,0
4,4344,CA,Butte (County),CHICO,95927,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
5,4344,CA,Butte (County),CHICO,95928,65,$0,22,$0,22,...,0,5,"$2,500",$0,$0,"$2,500",5,0,0,0
6,4344,CA,Butte (County),CHICO,95973,55,$0,14,$0,14,...,0,2,"$1,000",$0,$0,"$1,000",2,0,0,0
7,4344,CA,Butte (County),CLIPPER MILLS,95930,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
8,4344,CA,Butte (County),DURHAM,95938,12,$0,3,$0,3,...,0,1,$500,$0,$0,$500,1,0,0,0
9,4344,CA,Butte (County),FOREST RANCH,95942,2,$0,2,$0,2,...,0,0,$0,$0,$0,$0,0,0,0,0
10,4344,CA,Butte (County),GRIDLEY,95948,7,$0,5,$0,5,...,0,1,$500,$0,$0,$500,1,0,0,0
11,4344,CA,Butte (County),MAGALIA,95954,23,$0,12,$0,12,...,0,1,$500,$0,$0,$500,1,0,0,0
12,4344,CA,Butte (County),OROVILLE,95965,31,"$2,783",18,"$50,085",17,...,1,3,"$11,334",$0,"$1,570","$9,764",2,1,0,0
13,4344,CA,Butte (County),OROVILLE,95966,60,"$5,031",28,"$140,856",25,...,3,4,"$45,899","$31,114","$6,264","$8,521",2,1,1,1
14,4344,CA,Butte (County),PALERMO,95968,7,$0,2,$0,2,...,0,0,$0,$0,$0,$0,0,0,0,0
15,4344,CA,Butte (County),PARADISE,95969,37,$0,21,$0,21,...,0,2,"$1,000",$0,$0,"$1,000",2,0,0,0
16,4344,CA,Butte (County),RICHVALE,95974,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
17,4344,CA,Lake (County),CLEARLAKE,95422,144,"$67,487",42,"$2,834,464",11,...,24,35,"$366,275","$314,240","$19,295","$32,741",25,0,10,10
18,4344,CA,Lake (County),CLEARLAKE OAKS,95423,13,$0,7,$0,7,...,0,0,$0,$0,$0,$0,0,0,0,0
19,4344,CA,Lake (County),CLEARLAKE PARK,95422,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
20,4344,CA,Lake (County),CLEARLAKE PARK,95424,16,"$60,033",6,"$360,196",2,...,3,3,"$68,500","$64,344","$3,656",$500,1,0,2,2
21,4344,CA,Lake (County),CLEARLAKE PK,95423,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
22,4344,CA,Lake (County),COBB,95426,2,$0,2,$0,2,...,0,0,$0,$0,$0,$0,0,0,0,0
23,4344,CA,Lake (County),HIDDEN VALLEY LAKE,95467,12,$0,2,$0,2,...,0,1,$500,$0,$0,$500,1,0,0,0
24,4344,CA,Lake (County),KELSEYVILLE,95451,25,$0,7,$0,7,...,0,0,$0,$0,$0,$0,0,0,0,0
25,4344,CA,Lake (County),LAKEPORT,95453,24,$0,5,$0,5,...,0,0,$0,$0,$0,$0,0,0,0,0
26,4344,CA,Lake (County),LOCH LOMOND,95461,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
27,4344,CA,Lake (County),LOWER LAKE,95457,9,$0,6,$0,6,...,0,0,$0,$0,$0,$0,0,0,0,0
28,4344,CA,Lake (County),LUCERNE,95458,4,$0,4,$0,4,...,0,0,$0,$0,$0,$0,0,0,0,0
29,4344,CA,Lake (County),MIDDLETOWN,95461,5,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26814,4353,CA,Santa Barbara (County),SANTA BARBARA,93105,21,$289,3,$866,2,...,0,2,"$2,439",$866,"$1,573",$0,2,0,0,0
26815,4353,CA,Santa Barbara (County),SANTA BARBARA,93108,462,"$19,515",256,"$4,995,892",104,...,35,171,"$1,282,658","$835,910","$404,798","$41,949",137,13,21,21
26816,4353,CA,Santa Barbara (County),SANTA BARBARA,93109,5,$0,3,$0,3,...,0,0,$0,$0,$0,$0,0,0,0,0
26817,4353,CA,Santa Barbara (County),SANTA BARBARA,93110,11,$621,5,"$3,105",2,...,0,0,$0,$0,$0,$0,0,0,0,0
26818,4353,CA,Santa Barbara (County),SANTA BARBARA,93111,4,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26819,4353,CA,Santa Barbara (County),SANTA MARIA,93455,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26820,4353,CA,Santa Barbara (County),SANTA YNEZ,93460,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26821,4353,CA,Santa Barbara (County),SOLVANG,93463,3,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26822,4353,CA,Santa Barbara (County),SUMMERLAND,93067,6,$732,2,"$1,465",1,...,0,0,$0,$0,$0,$0,0,0,0,0
26823,4353,CA,Ventura (County),CAMARILLO,93010,3,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26824,4353,CA,Ventura (County),CAMARILLO,93012,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26825,4353,CA,Ventura (County),CARPINTERIA,93013,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26826,4353,CA,Ventura (County),CARPINTERIA,93014,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26827,4353,CA,Ventura (County),ENCINO,91436,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26828,4353,CA,Ventura (County),FILLMORE,93015,4,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26829,4353,CA,Ventura (County),MOORPARK,93021,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26830,4353,CA,Ventura (County),OAK VIEW,93022,19,"$5,730",5,"$28,652",1,...,0,4,"$37,665","$23,901","$9,572","$4,192",3,0,1,0
26831,4353,CA,Ventura (County),OJAI,93023,111,"$53,536",39,"$2,087,899",9,...,9,22,"$360,238","$318,524","$36,302","$5,411",11,3,8,7
26832,4353,CA,Ventura (County),OXNARD,93030,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26833,4353,CA,Ventura (County),OXNARD,93033,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26834,4353,CA,Ventura (County),OXNARD,93035,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26835,4353,CA,Ventura (County),OXNARD,93036,3,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26836,4353,CA,Ventura (County),PORT HUENEME,93041,2,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26837,4353,CA,Ventura (County),SANTA PAULA,93060,79,"$52,885",17,"$899,040",3,...,4,11,"$190,804","$133,509","$56,357",$938,4,5,2,1
26838,4353,CA,Ventura (County),SIMI VALLEY,93063,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26839,4353,CA,Ventura (County),THOUSAND OAKS,91360,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26840,4353,CA,Ventura (County),THOUSAND OAKS,91362,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
26841,4353,CA,Ventura (County),VENTURA,93001,148,"$39,743",29,"$1,152,558",13,...,6,12,"$208,095","$145,816","$31,040","$31,239",5,2,5,3
26842,4353,CA,Ventura (County),VENTURA,93003,507,"$122,874",35,"$4,300,581",8,...,19,4,"$50,831","$39,740","$10,018","$1,073",2,1,1,1
26843,4353,CA,Ventura (County),VENTURA,93004,5,$0,3,$0,3,...,0,0,$0,$0,$0,$0,0,0,0,0

In [50]:
katrina_fema

,disaster,state,county,city,zip,valid_registrations,avg_inspected_damage,total_inspected,total_damage,no_inspected_damage,...,damage_30000_max,approved_for_assistance,total_approved_amt,repair_replace_amt,rental_amt,other_needs_amt,approved_1_10000,approved_10001_25000,approved_25001_max,total_max_grants
1,1603,LA,Acadia (Parish),ABITA SPRINGS,70420,1,"$6,191",1,"$6,191",0,...,0,1,"$3,006",$0,"$2,000","$1,006",1,0,0,0
2,1603,LA,Acadia (Parish),BARATARIA,70036,1,"$55,392",1,"$55,392",0,...,1,1,"$25,311","$10,500","$2,000","$12,811",0,0,1,0
3,1603,LA,Acadia (Parish),BASILE,70515,3,$423,3,"$1,270",2,...,0,3,"$5,270","$1,270","$4,000",$0,3,0,0,0
4,1603,LA,Acadia (Parish),BATON ROUGE,70802,2,$647,2,"$1,294",0,...,0,1,"$5,850",$806,"$4,940",$104,1,0,0,0
5,1603,LA,Acadia (Parish),BATON ROUGE,70805,1,"$1,685",1,"$1,685",0,...,0,1,"$1,685","$1,685",$0,$0,1,0,0,0
6,1603,LA,Acadia (Parish),BATON ROUGE,70814,1,$201,1,$201,0,...,0,0,$0,$0,$0,$0,0,0,0,0
7,1603,LA,Acadia (Parish),BATONROUGE,70841,1,$0,1,$0,1,...,0,1,"$2,000",$0,"$2,000",$0,1,0,0,0
8,1603,LA,Acadia (Parish),BOGALUSA,70427,1,"$2,548",1,"$2,548",0,...,0,1,$791,$0,$0,$791,1,0,0,0
9,1603,LA,Acadia (Parish),BRANCH,70516,5,$61,3,$184,2,...,0,3,"$4,184",$184,"$4,000",$0,3,0,0,0
10,1603,LA,Acadia (Parish),CHURCH POINT,70525,21,$981,15,"$14,715",8,...,0,11,"$36,137","$8,032","$16,814","$11,291",10,1,0,0
11,1603,LA,Acadia (Parish),COVINGTON,70433,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
12,1603,LA,Acadia (Parish),COVINGTON,70435,1,$803,1,$803,0,...,0,1,"$2,791",$0,"$2,000",$791,1,0,0,0
13,1603,LA,Acadia (Parish),CROWLEY,70526,103,$908,73,"$66,272",52,...,0,39,"$101,188","$17,036","$58,466","$25,687",37,2,0,0
14,1603,LA,Acadia (Parish),CUTT OFF,70345,1,"$1,455",1,"$1,455",0,...,0,1,$791,$0,$0,$791,1,0,0,0
15,1603,LA,Acadia (Parish),DENHAM SPRINGS,70706,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
16,1603,LA,Acadia (Parish),DENHAM SPRINGS,70726,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
17,1603,LA,Acadia (Parish),DUSON,70529,1,$0,1,$0,1,...,0,1,"$2,000",$0,"$2,000",$0,1,0,0,0
18,1603,LA,Acadia (Parish),EGAN,70531,8,"$1,076",8,"$8,610",7,...,0,2,"$10,520","$5,200","$5,320",$0,2,0,0,0
19,1603,LA,Acadia (Parish),ESTHERWOOD,70534,10,"$2,946",10,"$29,459",7,...,0,4,"$13,106","$6,481","$5,234","$1,390",4,0,0,0
20,1603,LA,Acadia (Parish),EUNICE,70535,6,$0,5,$0,5,...,0,0,$0,$0,$0,$0,0,0,0,0
21,1603,LA,Acadia (Parish),EVANGELINE,70537,2,$0,2,$0,2,...,0,0,$0,$0,$0,$0,0,0,0,0
22,1603,LA,Acadia (Parish),FRANKLINTON,70438,1,"$3,645",1,"$3,645",0,...,0,1,"$2,000",$0,"$2,000",$0,1,0,0,0
23,1603,LA,Acadia (Parish),GONZALES,70737,1,$490,1,$490,0,...,0,0,$0,$0,$0,$0,0,0,0,0
24,1603,LA,Acadia (Parish),GRAMERCY,70052,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
25,1603,LA,Acadia (Parish),GREENSBURG,70441,1,$161,1,$161,0,...,0,0,$0,$0,$0,$0,0,0,0,0
26,1603,LA,Acadia (Parish),GRETNA,70053,2,"$2,475",2,"$4,951",0,...,0,2,"$5,363",$533,"$4,000",$831,2,0,0,0
27,1603,LA,Acadia (Parish),HAMMOND,70104,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
28,1603,LA,Acadia (Parish),HAMMOND,70403,1,$0,1,$0,1,...,0,1,"$2,000",$0,"$2,000",$0,1,0,0,0
29,1603,LA,Acadia (Parish),HARAHAN,70123,1,$0,1,$0,1,...,0,0,$0,$0,$0,$0,0,0,0,0
30,1603,LA,Acadia (Parish),HARVEY,70058,3,$0,2,$0,2,...,0,2,"$4,000",$0,"$4,000",$0,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
cleaning(housing_assistance)
cleaning(katrina_fema)

AttributeError: 'float' object has no attribute 'replace'

In [ ]:
katrina_fema.dtypes.value_counts()

In [176]:
housing_assistance.dtypes.value_counts()

int64     19
object     4
dtype: int64

In [177]:
housing_assistance.head()

,disaster,state,county,city,zip,valid_registrations,avg_inspected_damage,total_inspected,total_damage,no_inspected_damage,...,damage_30000_max,approved_for_assistance,total_approved_amt,repair_replace_amt,rental_amt,other_needs_amt,approved_1_10000,approved_10001_25000,approved_25001_max,total_max_grants
0,4344,CA,Butte,BANGOR,95914,54,48015,27,1296415,7,...,12,19,407336,344897,29154,33285,6,2,11,8
1,4344,CA,Butte,BERRY CREEK,95916,2,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,4344,CA,Butte,BIGGS,95917,10,0,5,0,5,...,0,1,500,0,0,500,1,0,0,0
3,4344,CA,Butte,CHICO,95926,66,0,21,0,21,...,0,3,1500,0,0,1500,3,0,0,0
4,4344,CA,Butte,CHICO,95927,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [178]:
disasters = pd.read_csv('materials/filtered_incident_type.csv')

disasters = disasters[['Disaster Number', 'Incident Type']]
disasters.head()

   Disaster Number Incident Type
0             4416         Flood
1             4416         Flood
2             4416         Flood
3             4416         Flood
4             4416         Flood

In [179]:
disaster_codes = (set(zip(disasters['Disaster Number'].values, disasters['Incident Type'].values)))

In [180]:
codes_dict = {num: dis for num, dis in disaster_codes}

In [181]:
housing_assistance['disaster_type'] = housing_assistance['disaster'].map(codes_dict)

In [182]:
housing_assistance.dropna(inplace=True)

In [183]:
housing_assistance.to_csv('materials/housing_cleaned.csv', index=False)